### ISSUE TITLE
error updating scifem

### ISSUE THREAD

**Issue by rsn766** [scientificcomputing/scifem#53]
Running a MAC M3
0.8 version of Fenicsx
Collecting scifem
  Downloading scifem-0.2.7.tar.gz (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 21.2 M
  Preparing metadata (pyproject.toml) ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/fenicsx-env/lib/python3.12/site-pac
al/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
.
.
.
ModuleNotFoundError: No module named 'scikit_build_core'
What did I do wrong?
Do you need full error

**Comment by finsberg** [comment]
Hi @rsn766 
Have you tried
```
conda install conda-forge::scifem
```
?

**Comment by rsn766** [comment]
Duh...THANK YOU!!!

**Comment by rsn766** [comment]
nope, spoke to soon.
SOLVER_RULE_UPDATE
failed

PackagesNotFoundError: The following packages are not available from current channels:

  - conda-forge::scifem

Current channels:

  - defaults
  - https://conda.anaconda.org/conda-forge

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by finsberg** [comment]
OK, maybe this is some new syntax (I just copied it from https://anaconda.org/conda-forge/scifem).
How about
```
conda install -c conda-forge scifem
```

**Comment by rsn766** [comment]
That was it! Thank you!!!!

**Comment by rsn766** [comment]
Probably still the same issue?
At first it installed, but when I went to VS, I get this error in install.
Error while loading conda entry point: conda-libmamba-solver (dlopen(/opt/anaconda3/lib/python3.11/site-packages/libmambapy/bindings.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.20.dylib
  Referenced from: <496442DC-0EDE-3705-A2B5-401A4FC0D733> /opt/anaconda3/lib/libmamba.2.0.0.dylib
  Reason: tried: '/opt/anaconda3/lib/libarchive.20.dylib' (no such file), '/opt/anaconda3/lib/python3.11/site-packages/libmambapy/../../../libarchive.20.dylib' (no such file), '/opt/anaconda3/lib/python3.11/site-packages/libmambapy/../../../libarchive.20.dylib' (no such file), '/opt/anaconda3/bin/../lib/libarchive.20.dylib' (no such file), '/opt/anaconda3/bin/../lib/libarchive.20.dylib' (no such file), '/usr/local/lib/libarchive.20.dylib' (no such file), '/usr/lib/libarchive.20.dylib' (no such file, not in dyld cache))
Error while loading conda entry point: conda-libmamba-solver (dlopen(/opt/anaconda3/lib/python3.11/site-packages/libmambapy/bindings.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.20.dylib
  Referenced from: <496442DC-0EDE-3705-A2B5-401A4FC0D733> /opt/anaconda3/lib/libmamba.2.0.0.dylib
  Reason: tried: '/opt/anaconda3/lib/libarchive.20.dylib' (no such file), '/opt/anaconda3/lib/python3.11/site-packages/libmambapy/../../../libarchive.20.dylib' (no such file), '/opt/anaconda3/lib/python3.11/site-packages/libmambapy/../../../libarchive.20.dylib' (no such file), '/opt/anaconda3/bin/../lib/libarchive.20.dylib' (no such file), '/opt/anaconda3/bin/../lib/libarchive.20.dylib' (no such file), '/usr/local/lib/libarchive.20.dylib' (no such file), '/usr/lib/libarchive.20.dylib' (no such file, not in dyld cache))

CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

**Comment by jorgensd** [comment]
This seems like a more fundamental issue: https://github.com/ContinuumIO/anaconda-issues/issues/13353

**Comment by rsn766** [comment]
So Switch to my PC?

**Comment by jorgensd** [comment]
> So Switch to my PC?

I am just trying to point out that this doesn’t seem to be related to the specific conda environment. For instance, have you tried making a new environment?

**Comment by rsn766** [comment]
Turns out it was an "I am an idiot" problem. installed fine once I put my head back on my shoulders!
